default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: podcaster_development
  primary_replica:
    <<: *default
    database: podcaster_development
    replica: true
  secondary:
    <<: *default
    database: podcaster_secondary_development
    migrations_paths: db/secondary_migrate
  secondary_replica:
    <<: *default
    database: podcaster_secondary_development
    replica: true

test:
  <<: *default
  database: podcaster_test
  user: root

production:
  primary:
    <<: *default
    database: podcaster_production
    username: podcaster
    password: <%= ENV['PODCASTER_DATABASE_PASSWORD'] %>
  primary:
    <<: *default
    database: podcaster_secondary_production
    username: podcaster
    password: <%= ENV['PODCASTER_SECONDARY_DATABASE_PASSWORD'] %>
    migrations_paths: db/secondary_migrate
