:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 5 %>
staging:
  :concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 5 %>
development:
  :concurrency: 2
:timeout: 8
:queues:
  - critical
  - default
  - mailers
  - low
  - bottom
:scheduler:
  :schedule:
    check_external_rss_feeds:
      cron: '0 0 * * * *'   # Runs every hour
      queue: bottom
      description: 'Loops through externally-hosted RSS feeds for new episodes'
      class: CheckExternalRssFeedsWorker
