:concurrency: 2
:timeout: 8
staging:
  :concurrency: 2
production:
  :concurrency: 2
:queues:
  - critical
  - default
  - mailers
  - low
  - bottom
:schedule:
  check_external_rss_feeds_worker:
    cron: '0 0 * * * *'   # Runs every hour
    queue: bottom
    description: 'Loops through externally-hosted RSS feeds for new episodes'
